apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
spec:
  selector:
    app: heart-disease-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8200
  type: LoadBalancer
